apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: test
          image: USER_DOCKER_HUB/eureka-server:__VERSION_PROJECT__
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  ports:
  - port: 8761
    nodePort: 30001
    targetPort: 8761
    protocol: TCP
    name: http
  type: NodePort
  selector:
    app: eureka-server

